### ISSUE TITLE
Error when "npm run watch"

### ISSUE THREAD

**Issue by dkozhevn** [RomainMazB/octobercms-bootstrap-boilerplate#1]
ERROR in ../blank-src/assets/javascript/app.js
Module not found: Error: Can't resolve '@fortawesome/fontawesome-free/js/all.min
.js' in 'c:\xampp\htdocs\october\themes\blank-src\assets\javascript'
 @ ../blank-src/assets/javascript/app.js 9:0-52
 @ ../blank-src/index.js

Windows 7, 10, xampp v3.2.4., nodejs12.18.1.

**Comment by RomainMazB** [comment]
Just to be sure before further investigation: have you perfectly run the `npm install` from the `themes/blank-src/` folder?

I know it can be confusing but you need to run the command two times to make it works:
The first time from the `themes/bootstrap-boilerplate` folder (actually I don't know how exactly it's called when you install it from the marketplace because I clone the repo everytime I need it) to install webpack and its dependencies, and a second time in the `/themes/blank-src/` (or the name you gives to your theme followed by `-src`) to install your theme's dependencies: bootstrap and fontawesome as defaults but you could add whichever package you want.

**Comment by dkozhevn** [comment]
Dear RomainMazB, 

Yes, I run npm install twice:
first time from **themes/bootstrap-boilerplate**, the second time from **themes/blanc-src**

Exactly as mentioned in the documentation.

**Comment by RomainMazB** [comment]
@dkozhevn
Ok, I found my crap: I've just forgot to add FontAwesome in the project's devDependency.

[Just add this line](https://github.com/RomainMazB/octobercms-bootstrap-boilerplate/pull/2/commits/0e05454232296af36058ce6efecf71e4050d3317#diff-6caf3cefe4aa59ed8b7ed4bca551ab85R28) into your `/themes/blank-src/packages.json`
and re-run `npm install`, or remove/re-install the theme from scratch.

I've also removed/modified some useless/unused files but you don't need to do these modifications to see the boilerplate works.

Let me know if it's ok for you! Have fun!

**Comment by dkozhevn** [comment]
Thanks!

Working now.

Unfortunately, It seems impossible to change review on OctoberCMS marketplace.

**Comment by RomainMazB** [comment]
@dkozhevn yeah I know, it's a [requested feature](https://github.com/octobercms/october/issues/3942).

No worries that's nothing. It's a free theme: the only one who may be blessed is my honor (joke) and the users who will not read my answer to your review saying it's fixed in the latest version so they will go away and not profit this awesome tool(totally subjective :joy:)

The themes are not updatable from the CMS, so you won't be noticed if I update it. If you want to be noticed, follow me on Twitter: @RBilloir .

**Comment by RomainMazB** [comment]
@dkozhevn your review was deleted on the marketplace so you can create another one. Let me know if you encounter any other problem!

**Comment by dkozhevn** [comment]
Thanks and good luck!
